Updates to user profile - Task #25
ibm-cds-labs/sodashboard pull request #90
Opened 2017-08-07 19:31 UTC by mmcelaney

Remove slack id and slack name, add slack organization. Changing stack overflow id to stack overflow url. resolving conflicts with other branch. This is related to Task #25.

2017-08-15 13:04 UTC, lornajane requested changes
This doesn't match what I expected to see when I run this locally.  There are two sets of changes; changing the fields on the profile page, and adding links to people's stackoverflow accounts which should probably be in multiple places where the person's information is used.

On the profile page:
 - don't display the slack ID.  This change seems to remove both the slack ID and the slack name, the name field should stay as it was.
 - add a field for Slack Organisation.  The form elements are visually correct and the label is good, but when I type into the new field, it also fills in another field on the form, they are somehow linked or copy/pasted to be the same?  Please test the field before opening the pull request.
- There is an unexpected change to the stackoverflow ID field.  This field doesn't need to change at all.

Elsewhere in the system, stackoverflow usernames are linked to stackoverflow but these should link to the "topactivity" tab rather than just the user's home page.

Let me know if any of that doesn't make sense or if you have questions!

2017-08-15 14:40 UTC, downasaurus commented
@lornajane AH ok so don't replace SO ID with profile, ADD SO profile as an option.  I thought Slack ID was populating the name and that's not something we wanted. I did NOT experience the issue you experienced while testing. Everything worked for me locally when I tested. Can you paste a screenshot of what you saw or can we meet to recreate the issue?

Here is the original task:
"
    Link to user's SO profile, e.g. http://stackoverflow.com/users/5244530/ptitzler (my suggestion would be to link to the activity summary tab http://stackoverflow.com/users/5244530/ptitzler?tab=topactivity because it provides the most useful information)
    Remove Slack ID from profile display (seems to serve no real purpose + cannot be changed)
    Add link to Slack team

2017-08-15 14:40 UTC, mmcelaney commented
@lornajane AH ok so don't replace SO ID with profile, ADD SO profile as an option. I thought Slack ID was populating the name and that's not something we wanted. I did NOT experience the issue you experienced while testing. Everything worked for me locally when I tested. Can you paste a screenshot of what you saw or can we meet to recreate the issue?

Here is the original task:
"
Link to user's SO profile, e.g. http://stackoverflow.com/users/5244530/ptitzler (my suggestion would be to link to the activity summary tab http://stackoverflow.com/users/5244530/ptitzler?tab=topactivity because it provides the most useful information)
Remove Slack ID from profile display (seems to serve no real purpose + cannot be changed)
Add link to Slack team

2017-08-16 21:53 UTC, mmcelaney reviewed
ok updated based on feedback. proposing the stack overflow profile link become a new task.

2017-08-16 22:08 UTC, mmcelaney commented
Made Task #92 to accommodate the SO Profile ask.

2017-08-22 12:54 UTC, merged

2017-08-22 12:58 UTC, lornajane commented
Merged with thanks :)